(def close-encounters [(->Note :D 3 1/2)
                       (->Note :E 3 1/2)
                       (->Note :C 3 1/2)
                       (->Note :C 2 1/2)
                       (->Note :G 2 1/2)])

(def ff-fanfare [(->Note :A# 4 1/8)
                 (->Note :G# 4 1/8)
                 (->Note :A# 4 1/8)
                 (->Note :G# 4 1/16)
                 (->Note :C# 5 1/8)
                 (->Note :C# 5 1/16)
                 (->Note :C 5 1/8)
                 (->Note :C# 5 1/16)
                 (->Note :C 5 1/8)
                 (->Note :C 5 1/8)])
